import torch
import torch.nn as nn
from torchinfo import summary
import torchvision.models as models

# Load ResNet-50 model
model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)

# Display the model summary with detailed info using torchinfo
model_summary = summary(model, input_size=(1, 3, 224, 224), verbose=2)

def calculate_sgemm_macs(conv_layer_info):
    """Calculate MACs for SGEMM for each convolution layer, taking im2col into account"""
    total_macs = 0
    
    # Simulate batch size of 1 for this example
    batch_size = 1
    
    # Parse through each convolution layer's info
    for layer in conv_layer_info:
        conv_module = layer.module
        
        if isinstance(conv_module, nn.Conv2d):
            # Get the input/output shapes directly from torchinfo
            in_channels = conv_module.in_channels  # Input channels
            out_channels = conv_module.out_channels  # Output channels
            input_h, input_w = layer.input_size[2:]  # Input height and width
            kernel_h, kernel_w = conv_module.kernel_size  # Kernel height and width
            
            # Create a dummy input tensor of appropriate shape
            input_tensor = torch.randn((batch_size, in_channels, input_h, input_w))
            
            # Simulate im2col operation using unfold (which does the im2col operation)
            unfolded_input = input_tensor.unfold(2, kernel_h, conv_module.stride[0]).unfold(3, kernel_w, conv_module.stride[1])
            
            # The unfolded shape simulates the columns generated by im2col
            # For example, if input is (1, in_channels, H, W) -> unfolded will have shape (1, in_channels, out_h, out_w, kernel_h, kernel_w)
            out_h, out_w = unfolded_input.shape[2:4]
            unfolded_input = unfolded_input.reshape(batch_size, in_channels * kernel_h * kernel_w, out_h * out_w)
            
            # SGEMM will operate on the unfolded input and the weights of the conv layer
            # MACs = in_channels * kernel_h * kernel_w * out_channels * output_h * output_w
            macs = in_channels * kernel_h * kernel_w * out_channels * out_h * out_w
            total_macs += macs
            
            # Display layer info and MACs
            print(f"Layer: {conv_module} - Input Shape after im2col: {unfolded_input.shape}, Output Shape: [{batch_size}, {out_channels}, {out_h}, {out_w}], MACs = {macs}")
    
    print(f"Total SGEMM MACs: {total_macs}")

# Extract convolution layer details from the model summary
conv_layers_info = [
    layer for layer in model_summary.summary_list
    if isinstance(layer.module, nn.Conv2d)
]

# Calculate MACs for SGEMM
calculate_sgemm_macs(conv_layers_info)
